version: 2.1
orbs:
  slack: circleci/slack@3.4.2

jobs:
  build:
    docker:
      - image: 218546966473.dkr.ecr.us-east-1.amazonaws.com/circle-ci:stitch-tap-tester-uv
    steps:
      - checkout
      - run:
          name: 'Setup virtual env'
          command: |
            uv venv --python 3.12 /usr/local/share/virtualenvs/tap-recurly
            source /usr/local/share/virtualenvs/tap-recurly/bin/activate
            uv pip install -U pip setuptools
            uv pip install .[dev]
      - run:
          name: 'JSON Validator'
          command: |
            source /usr/local/share/virtualenvs/tap-tester/bin/activate
            stitch-validate-json tap_recurly/schemas/*.json
      - run:
          name: 'pylint'
          command: |
            apt-get update && apt-get install -y make
            source /usr/local/share/virtualenvs/tap-recurly/bin/activate
            make lint
      - run:
          name: 'Integration Tests'
          command: |
            source /usr/local/share/virtualenvs/tap-tester/bin/activate
            uv pip install --upgrade awscli
            aws s3 cp s3://com-stitchdata-dev-deployment-assets/environments/tap-tester/tap_tester_sandbox dev_env.sh
            source dev_env.sh
            run-test --tap=tap-recurly tests
      - slack/notify-on-failure:
          only_for_branches: master

workflows:
  version: 2
  commit:
    jobs:
      - build:
          context:
            - circleci-user
            - tap-tester-user

  build_daily:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build:
          context:
            - circleci-user
            - tap-tester-user
